### ISSUE TITLE
[BUG][shared_memory] Error when transfer numpy array

### ISSUE THREAD

**Issue by lehoangnam040** [FI-Mihej/Cengal#1]
Hi, I got this exception when run my sample [code](https://github.com/lehoangnam040/Learning-everyday/tree/main/python/cengal) in 2 separate terminal using `cengal` to test ipc transfer a numpy array:
```
$ python smem_sender.py
```
```
$ python smem_receiver.py
```

- Error
```
Traceback (most recent call last):
  File "smem_sender.py", line 46, in <module>
    main()
  File "smem_sender.py", line 35, in main
    creator.put_message(x)
  File "/home/ubuntu/python-venv/playaround/lib/python3.8/site-packages/cengal/hardware/memory/shared_memory/versions/v_0/shared_memory.py", line 2324, in put_message
    mapped_obj, offset, message_offset = self.write_message(obj)
  File "/home/ubuntu/python-venv/playaround/lib/python3.8/site-packages/cengal/hardware/memory/shared_memory/versions/v_0/shared_memory.py", line 2309, in write_message
    mapped_obj, offset, size = self.put_obj(obj)
  File "/home/ubuntu/python-venv/playaround/lib/python3.8/site-packages/cengal/hardware/memory/shared_memory/versions/v_0/shared_memory.py", line 2273, in put_obj
    mapped_obj, offset, size = codec.map_to_shared_memory(self, obj)
  File "/home/ubuntu/python-venv/playaround/lib/python3.8/site-packages/cengal/hardware/memory/shared_memory/versions/v_0/shared_memory.py", line 279, in map_to_shared_memory
    write_uint64(shared_memory.base_address, offset + bs * len(BaseObjOffsets) + bs * BytesOffsets.data_size, data_size)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

- environments:
```
os                           x86_64
ubuntu                    22.04
python                    3.8.18
cengal                    4.0.3
cengal-light              4.0.3
```

- The log points out that `offset` is `None` in this line
https://github.com/FI-Mihej/Cengal/blob/9a2e728ab13704927a2403e498ae5c5b5e7188b4/cengal/hardware/memory/shared_memory/versions/v_0/shared_memory.py#L277-L278

- I can help to fix but not sure if I can understand the logic behind `malloc` function quickly

**Comment by FI-Mihej** [comment]
@lehoangnam040 Hi Lê Hoàng Nam, thank you for your report. Numpy arrays are not yet supported directly. However, I will look deeply into the issue within the next day or two. I believe I will be able to add some support for Numpy arrays shortly.

**Comment by lehoangnam040** [comment]
The reason is not really about numpy array, as I passed the np array as  `bytes` via `nparray.tobytes()`.
Even if I do `creator.put_message(b"1"*6000)` it would be the same error, so probably the reason here is about the large `bytes`

**Comment by FI-Mihej** [comment]
@lehoangnam040 Hi Lê Hoàng Nam,
I've updated Cengal to v4.3.1. It has fix for current issue among other changes. Also I've added a starter support for Numpy arrays to be shared between processess. Feel free to look to new examples: [Shared memory examples](https://fi-mihej.github.io/Cengal/#examples_2)

**Comment by lehoangnam040** [comment]
Hi, I've tested and this issue is gone but it's also another is `FreeMemoryChunkNotFoundError`. May I ask what is this?

**Comment by FI-Mihej** [comment]
@lehoangnam040, Hi! I just came across your new comment. To ensure I don't miss future updates, it would be great if you could open a new issue for any new concerns. This way, I can directly see notifications for new issues from GitHub's UI.

`FreeMemoryChunkNotFoundError` exception indicates that an unpartitioned chunk of memory of requested size not being found.

Regarding this error, it’s important to adjust the size parameter in the SharedMemory configuration. Trying to estimate memory consumption down to the byte is not practical because it fails to account for the memory overhead required by each entity stored (such as entity type metadata, pointers to child entities, etc.).

When setting the `size` parameter for SharedMemory, consider using broader units like tens (for embedded systems), hundreds, or thousands of megabytes, rather than precise byte counts. This approach is similar to how you would not precisely calculate the amount of memory needed for a web server hosted externally; you make an educated guess, like assuming that 256 MB might be insufficient but 768 MB could be adequate, and then adjust based on practical testing.

Also, be aware of memory fragmentation, which affects all memory allocation systems, including the OS itself. For example, if you have a SharedMemory pool sized to store exactly ten 64-bit integers, accounting for additional bytes for system information, your total might be around 200 bytes. Initially, after storing the integers, your memory might appear as ["int", "int", ..., "int"]. If you delete every second integer, the largest contiguous free memory chunk could be just 10 bytes, despite having 50 bytes free in total. This fragmentation means you cannot store a larger data structure like a 20-byte string which needs contiguous space.

To resolve this, simply increase the `size` parameter value of SharedMemory. This is akin to how you would manage memory allocation for server hosting or thread stack sizes in software development.
