### ISSUE TITLE
Whitespace in filename causing Bazel Python build rules to break

### ISSUE THREAD

**Issue by akavalar** [FI-Mihej/Cengal#3]
Hi, it looks like Bazel python build rules break when trying to build Cengal due to a whitespace in one of the data files. Would it be possible to replace it with an underscore or similar? Thanks! 

```
.../build-runfiles (args bazel-out/k8-opt/bin/...runfiles_manifest bazel-out/k8-opt/bin/...runfiles): link or target filename contains space on line 10415: 'python3_deps_pypi__cengal_light/site-packages/cengal/user_interface/console/encoding_changer/versions/v_0/data/data/Leoš Janáček.py .../external/python3_deps_pypi__cengal_light/site-packages/cengal/user_interface/console/encoding_changer/versions/v_0/data/data/Leoš Janáček.py'
```

file: https://github.com/FI-Mihej/Cengal/blob/master/cengal/user_interface/console/encoding_changer/versions/v_0/data/data/Leo%C5%A1%20Jan%C3%A1%C4%8Dek.py

**Comment by FI-Mihej** [comment]
Hi @akavalar , I have no experience with Bazel. Are you trying to build Cengal with Bazel? Cengal has its own compilation and build system based on SetupTools and has not been adjusted or tested for Bazel. The Cengal build system recognizes that the `Leoš Janáček.py` file is a data file, not a source code file (this file lies in `data` dir).

However, feel free to rename or remove this file; it is useful only for testing purposes.

# Build from sources

1. If you need to compile and build your own single Cengal wheel for current environment, instead of using the wheels provided on PyPi, please consider the notes from the [Build from sources](https://github.com/FI-Mihej/Cengal#build-from-sources) and then follow the next instructions:

```shell
git clone https://github.com/FI-Mihej/Cengal.git
cd ./Cengal
./prepare__setup.sh
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade setuptools
python3 -m pip install --upgrade wheel
python3 -m pip install --upgrade auditwheel
python3 -m pip install -r ./requirements.txt
python3 -m pip wheel ./ -w ./wheelhouse/
auditwheel repair ./wheelhouse/cengal-*-linux_x86_64.whl -w ./wheelhouse_result/
```

You'll find your wheel in the `./wheelhouse_result` folder. Feel free to install it locally by placing it in your current installation directory and running a command like `python3 -m pip install %YourWheelFileName%.whl`

2. In order to build the source distribution (sdist), please consider the notes from the [Build from sources](https://github.com/FI-Mihej/Cengal#build-from-sources) and then use the following build steps instead:

```shell
git clone https://github.com/FI-Mihej/Cengal.git
cd ./Cengal
./prepare__setup.sh
python3 setup.py sdist
```

You'll find your `cengal-4.4.0.tar.gz` sdist file in the `./dist` folder. Feel free to build and install it locally by placing it in your current installation directory and running a command like `python3 -m pip install cengal-4.4.0.tar.gz`. However, please note that, unlike with wheels, installing an sdist file initiates the compilation process during each installation session.

3. In order to install it in dev-mode, please follow the instructions in [Build from sources](https://github.com/FI-Mihej/Cengal#build-from-sources). The command `sudo chown -R $(id -u):$(id -g) .` in the `install_in_dev_mode.sh` script can be ignored and commented out; I need it to restore repository files' user permissions after building the wheel under the Docker containers.

If you have any additional questions, please feel free to use either [Discussions](https://github.com/FI-Mihej/Cengal/discussions) or [Cengal Discord](https://discord.gg/TAy7xNgR)

**Comment by FI-Mihej** [comment]
@akavalar  I think I've got your point now. This file is among the installed files in `site-packages`, which breaks some Bazel commands that try to traverse through all third-party dependencies' files. I've just read about Bazel. It seems Bazel expects its own specific rules to be used by every existing third-party dependency, which is a questionable approach considering that Bazel-based packages are only a small portion of available Python packages.

I'll review my build setup. I think it would not be a problem to remove this file from the sdist or wheels in general. I'll check.

In the meantime, please either manually rename/remove that file or adjust your Bazel-based project configuration to perform such renaming either as part of your build process or as a general preprocessing step.

**Comment by FI-Mihej** [comment]
@akavalar I've removed this file. Please wait for the next release (I plan to make it by next Monday).
